Date::DATE_FORMATS[:date_input_field] = '%m/%d/%Y'
Date::DATE_FORMATS[:datetime_input_field] = '%m/%d/%Y %l:%M %P'
Date::DATE_FORMATS[:time_input_field] = '%l:%M %P'
Time::DATE_FORMATS[:date_input_field] = '%m/%d/%Y'
Time::DATE_FORMATS[:datetime_input_field] = '%m/%d/%Y %l:%M %P'
Time::DATE_FORMATS[:time_input_field] = '%l:%M %P'
